# Generated by Django 5.1 on 2024-08-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cereated_at',
            new_name='created_at',
        ),
    ]
