# Generated by Django 5.1 on 2024-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_cereated_at_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deu_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
